version: "3"

services:
  neo4j:
    container_name: Database
    image: ${NEO4J_DOCKER_IMAGE}
    ports:
       - "${BACK_PORT}:6362"
    #   - "${HTTP_PORT}:7474"
    #   - "${BOLT_PORT}:7687"
    volumes:
      - ./DataBase/data:/data
      - ./DataBase/logs:/logs
      - ./DataBase/backups:/backups
      - ./DataBase/import:/import
      - ./DataBase/metrics:/metrics
      - ./DataBase/conf:/var/lib/neo4j/conf
      - ./DataBase/ssl:/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - server_server_backup_enabled=true
      - server_backup_listen_address=0.0.0.0:${BACK_PORT}
      - dbms_security_procedures_unrestricted=apoc.*
    # This status can be checked using the "docker ps" command.
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    networks:
      - mynetwork

  dj:
    container_name: API
    build: ./DjangoApp
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - ./DjangoApp:/code
    ports:
      - "${DJANGO_EXTERNAL_PORT}:${DJANGO_PORT}"
    environment:
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_PORT=${NEO4J_PORT}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_ENDPOINT=${NEO4J_ENDPOINT}
      - UI_HOST=${UI_HOST}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_HOST=${DJANGO_HOST}
    depends_on:
      - neo4j
    networks:
      - mynetwork

  ng:
    container_name: UI
    build: AngularUI
    ports:
      - "${ANGULAR_EXTERNAL_PORT}:${ANGULAR_PORT}"
    environment:
      - APP_API_ENDPOINT=${APP_API_ENDPOINT}
    depends_on:
      - dj
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge